name: Deploy to EC2

on:
  push:
    branches:
      - dev  # dev 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ~/KDEV_Univ_Camp_BE
            git pull origin dev
            sudo ./gradlew clean
            sudo ./gradlew build
            java -jar ./build/libs/jwt-tutorial-0.0.1-SNAPSHOT.war
